[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "video-annotator"
version = "0.1.0"
description = "Tools for video annotation and analysis of headcasting data"
authors = [
    { name="Hind Al Ali", email="hind@ucsb.edu" }
]
readme = "README.md"
requires-python = ">=3.8"

[tool.setuptools.packages.find]
where = ["."]
exclude = ["headcast/notebooks*"]